[tool.poetry]
name = "euddraft"
version = "0.9.9.7"
description = "Framework for creating & applying various plugins to StarCraft map."
authors = ["armoha <kein0011@naver.com>", "Park Hyun Woo <phu54321@naver.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.10, < 3.12"
cx-Freeze = "^6.14.7"
eudplib = "^0.75.0.dev2"
colorama = "^0.4.6"
openpyxl = "^3.1.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
